### ISSUE TITLE
Performance issue with latest nextjs 13

### ISSUE THREAD

**Issue by M1ck0** [vercel/analytics#13] opened 2022-10-30 20:52 UTC
The app is deployed on Vercel normally, but when loading the app, there is a script file that loads for 1+ sec. Here is screenshot

<img width="1042" alt="Screenshot 2022-10-30 at 21 26 54" src="https://user-images.githubusercontent.com/19279947/198900968-f30a421f-76ce-4fdc-a466-b1901c210888.png">

When I removed analytics package, website loaded much faster and FCP was much lower.

**Comment by timolins** [comment] 2022-10-31 09:43
Hi there! Mind sharing a preview URL for this?

**Comment by M1ck0** [comment] 2022-10-31 11:41
@timolins 

It is currently on my work-in-progress website. Here is the link [https://www.miletadulovic.me/](https://www.miletadulovic.me/)

When you do a hard reload Command + Shift + R (Ctrl + Shift + R) while the network tab is open in the console, you'll see `script.js` file that is 1.1-1.3 kb heavy and loading for a long time. I just rechecked it, It took 3.57 sec.

This really reduces page speed score on both Vercel analytics, and Google Page Speed analytics. I first wasn't sure from where is this coming, but after disabling Vercel analytics, this file vanished from the network tab.

<img width="1379" alt="Screenshot 2022-10-31 at 12 38 27" src="https://user-images.githubusercontent.com/19279947/198999408-3bdf1773-3193-4615-928f-8598bd4313bb.png">

Here are the headers for this file
<img width="1180" alt="Screenshot 2022-10-31 at 12 39 18" src="https://user-images.githubusercontent.com/19279947/198999534-4975ae01-9116-4c1f-9fae-9168ab9513ce.png">

<img width="1178" alt="Screenshot 2022-10-31 at 12 39 45" src="https://user-images.githubusercontent.com/19279947/198999623-e0f85fe7-1abf-4d03-ac19-e5b930a23a3b.png">

**Comment by M1ck0** [comment] 2022-11-04 09:12
Any updates on this? @timolins

**Comment by tobiaslins** [comment] 2022-11-04 11:23
@M1ck0  I saw that the script is currently embedded on your page and did several speed score tests (Google Page Speed, etc) and did not see anything poping up because of that longer script load time. (It's `async` and soon `defer` so will not block anything) 
Can you share us some results that shows the script impacts your page?

**Comment by M1ck0** [comment] 2022-11-04 20:01
@timolins Here are the screenshots

<img width="968" alt="Screenshot 2022-11-04 at 20 51 54" src="https://user-images.githubusercontent.com/19279947/200063671-1ac8404d-a06e-4d83-a35b-75f20cfed021.png">
<img width="877" alt="Screenshot 2022-11-04 at 20 57 20" src="https://user-images.githubusercontent.com/19279947/200063933-f14e5762-c4f4-4fe1-9f69-d88e7b1b8bff.png">


Take a look at Time to Interactive and Total Blocking time. The difference is enormous.

Also, look at the treemap, when is the first frame presented to a user?

Are you sure that you can't see anything wrong with this? And let me also say that the page I am testing is just a page with few lines of text, no API calls, no interactions, or anything.

When I removed `@vercel/analytics` it was much better. With that package when I try to load the site in incognito, I always see blank (white) screen for like second or two (based on my connection) and then page appears.

**Comment by timolins** [comment] 2022-11-07 14:41
Interesting, thanks for investigating! Mind sharing a preview deployment link with us that has Audiences enabled? So we can compare as well.

**Comment by M1ck0** [comment] 2022-11-07 14:55
I'll send you a link in few hours.

**Comment by M1ck0** [comment] 2022-11-07 18:56
I added it to the main deployment so you can go check it there.

[miletadulovic.me](https://miletadulovic.me)

**Comment by timolins** [comment] 2022-11-10 11:53
The initial issue you mentioned appeared to be caused by Cloudflare, which sits in-front of your deployment. We recently switched to a more loose caching policy, allowing Cloudflare to cache the script, which should resolve the issue you mentioned. 

To make sure, I made an experiment that compares the Next.js 13 starter in 4 different environments:
* Without Audiences
* With Audiences
* Without Audiences + Cloudflare
* With Audiences + Cloudflare

A ran this test multiple times and there was no notable difference for environments that had Audiences enabled.

<img width="1571" alt="image" src="https://user-images.githubusercontent.com/1440854/201081361-3e9a1c68-20ee-45e0-b405-2b495d0f5e9d.png">

I'll close this issue for now.

---
It might be worth to experiment with removing Google Tag Manager as well, which could be the cause of the slow down.

**Closed by timolins** 2022-11-10 11:53 UTC
