### ISSUE TITLE
Nuxt: window is not defined

### ISSUE THREAD

**Issue by larrasu** [vercel/analytics#157] opened 2024-11-15 03:46 UTC
I followed the [documentation](https://vercel.com/docs/analytics/quickstart) to a T and got the error `window is not defined` when I try to add the `<Analytics/>` on the `app.vue`.

**Comment by feugy** [comment] 2024-11-15 08:39
Hello @larrasu, thanks for the bug report.

Could you share a reproduction please?
We have a working example for [Nuxt](https://github.com/vercel/analytics/blob/main/apps/nuxt/app.vue), and one for [vue](https://github.com/vercel/analytics/blob/main/apps/vue/src/App.vue), so I'll need your help to find out what's wrong.

**Comment by Viserion77** [comment] 2024-11-18 21:46
Same here!
I have a sample of the bug in this branch:
[feat-add-@vercel/analytics](https://github.com/Viserion77/supertool.digital/tree/feat-add-%40vercel/analytics)

to run the project and see the error just install the dependencies and run `npx nuxt dev`

**Comment by Viserion77** [comment] 2024-11-18 22:46
Trying to trace the origin of the error...

I believe everything starts here:
https://github.com/vercel/analytics/blob/68d0d13d60e7d0672a33c1a1b3f0624e1b137ecd/packages/web/src/nuxt/index.ts#L2-L5

For Nuxt, the createComponent from Vue is being used. In turn, inside the setup function, there's a validation on the window prop, which causes the error to occur:
https://github.com/vercel/analytics/blob/68d0d13d60e7d0672a33c1a1b3f0624e1b137ecd/packages/web/src/vue/create-component.ts#L22

I'm studying SSR in Nuxt, and I noticed that window only exists after Vue's mounted lifecycle hook...

This even makes me question whether analytics works in this kind of architecture, since everything fails during the injection in this validation:
https://github.com/vercel/analytics/blob/68d0d13d60e7d0672a33c1a1b3f0624e1b137ecd/packages/web/src/generic.ts#L45

**Comment by feugy** [comment] 2024-11-19 16:51
Hey folks!
I'm able to reproduce this. Very annoyingly, this does not happen on the example app, possibly because of intra-monorepo dependencies.

@Viserion77 Analytics should only happen in client side, when a user actually visit your page. So it's expected that we skip everything when (pre)rendering the page on server side.

**Comment by feugy** [comment] 2024-11-19 17:21
@larrasu, @Viserion77 thanks again for the bug report. Version 1.4.1 is out.

I'll close this bug, please re-open it if the fix isn't working as expected !

**Closed by feugy** 2024-11-19 17:21 UTC
