### ISSUE TITLE
Getting 404 for `script.js`

### ISSUE THREAD

**Issue by bogy0** [vercel/analytics#1] opened 2022-10-25 21:59 UTC
First of all, great work with the updates. Watching the conference was really inspiring.
Of course, my first thing to do was to update one of my Next.js projects and try the new goodies.

At one point I decided to try out this new Analytics feature called Audiences, but after adding it to the project I am getting these errors in the console.
![Screenshot 2022-10-25 at 23 46 55](https://user-images.githubusercontent.com/5119480/197888723-2a6c03b5-bc6f-4fc5-9fd7-3bc69f1b0fff.png)

After some quick search in the vercel org I came across this repository where I found a [reference](https://github.com/vercel/analytics/blob/32c734a391014b36662f40c35e1f3e4832d0b74f/packages/web/src/generic.ts) for this `va/script.js` file.
![Screenshot 2022-10-25 at 23 50 22](https://user-images.githubusercontent.com/5119480/197888894-5a22e4dc-6814-4fa5-b411-230a84626f2e.png)

Overall, the audiences feature is working, I am getting visitor data in the newly enabled dashboard page; the issue only is that the browser logging this error.

If you need further details, example codes, let me know, but what i did was basically follow your guide:
- install `@vercel/analytics`
- import and place the `Analytics` react component into the `_app.jsx` file, like this:

```
import { Analytics } from '@vercel/analytics/react';

import '../styles/globals.css'

const MyApp = ({Component, pageProps }) => {
  return (
      <>
        <Component {...pageProps} />
        <Analytics />
      </>
  );
}

export default MyApp
```

**Comment by frontsideair** [comment] 2022-10-25 22:15
I'm also having a similar problem. I don't get any analytics data on my dashboard though.

I added this to my Gatsby project by adding `inject` to `gatsby-browser.js`, which does its job and adds the script to the `<head>`. But the `va/script.js` gives a 404, which makes sense because there's no such file anywhere. Is Vercel supposed to intercept and serve this file?

I also have [rewrites](https://vercel.com/docs/project-configuration#project-configuration/rewrites) defined in my project so maybe this is overriding the hypothesized intercept. This may be an edge case.

**Comment by NuroDev** [comment] 2022-10-26 00:01
> But the va/script.js gives a 404, which makes sense because there's no such file anywhere. Is Vercel supposed to intercept and serve this file?

Yeah same here. Have another site that has this package working & manually added the `/va/script.js` to my `public/` directory but then got another error from failing to post to `/va/view`.

Does seem like it's usually expected that Vercel will add / intercept any requests to `/va/...` endpoint(s) but it isn't for some reason?

**Comment by alex-grover** [comment] 2022-10-26 03:59
Seeing a 404 as well with an Astro project.

**Comment by max** [comment] 2022-10-26 04:23
Possibly not the reason y'all are seeing the error but I was also getting a 404 for the injected script when deploying `@vercel/analytics`. Turns out you first have to enable the feature in the dashboard and then deploy the library (a re-deploy fixed it for me).

**Comment by bogy0** [comment] 2022-10-26 08:14
Unfortunately, re-deploying my project is not solved the error log in my case.

**Comment by chriswdmr** [comment] 2022-10-26 08:41
As @max correctly pointed out, the mentioned path `/va/script.js` will become available on your next deployment **after** you enabled the feature.

If you added the package before you enabled the feature, you can trigger a redeployment which have the same effect.

@bogy0 It seems like the error you're seeing is related to your browser as you already get data. Have you tried disabling all extensions/ad-blockers?

**Comment by egger** [comment] 2022-10-26 10:24
Same problem here. I´ve already tried all steps (re-deploying, enabling/disabling, etc.) but still have the same error as @bogy0.

**Comment by chriswdmr** [comment] 2022-10-26 10:38
Would you mind creating a minimal reproduction?

Ideally a small repo that gets deployed to Vercel so we can have a closer look!

**Comment by bogy0** [comment] 2022-10-26 11:13
will do later today

**Comment by egger** [comment] 2022-10-26 11:33
I´ve also a simple app if you want to take a look

**Comment by frontsideair** [comment] 2022-10-26 11:51
I also tried redeploying but didn't work in my case. It's not minimal but [my blog](https://github.com/frontsideair/blog), for which I want to use the analytics, is open-source.

**Comment by chriswdmr** [comment] 2022-10-26 12:46
>I also tried redeploying but didn't work in my case. It's not minimal but [my blog](https://github.com/frontsideair/blog), for which I want to use the analytics, is open-source.

Thanks for providing an example!

It seems like that your custom 404 page is catching all routes – including the `/va/script.js` URL.
You have to instrument Gatsby in a way that it ignores this URL.

**Comment by frontsideair** [comment] 2022-10-26 14:42
Thanks, I added the redirect manually to bypass Gatsby with the [this config](https://github.com/frontsideair/blog/blob/main/rewrites.json#L10-L14), which is transformed with [gatsby-plugin-zeit-now](https://www.gatsbyjs.com/plugins/gatsby-plugin-zeit-now/) plugin. This fixed the 404 issue and requests are actually sent and response is received, but my dashboard doesn't load any data.

**Comment by chriswdmr** [comment] 2022-10-26 15:13
@frontsideair the script is available behind your own domain and not via `vercel.com`. 
Please change `vercel.com` to your own domain.

**Comment by frontsideair** [comment] 2022-10-26 15:55
I understand and removed the redirect to `vercel.com`, I haven't found a good workaround so I'm giving up on this for now. Waiting for an official solution.

**Comment by mehulmpt** [comment] 2022-10-26 19:04
Same for us. With rewrites enabled the @vercel/analytics script throws 404.

**Comment by GizmoRay** [comment] 2022-10-26 21:04
+1 - facing the same issue. Some guidance on how best to handle both a 404 page + allowing the analytics package to come through would be great.

**Comment by pyronaur** [comment] 2022-10-27 05:40
I created a static blank `/va/script.js` on my Astro site in hopes that would get replaced, but looks like that didn't do anything either.

**Comment by vojto** [comment] 2022-10-27 08:24
Same issue with SvelteKit.

**Comment by schnubor** [comment] 2022-10-27 14:31
Having the same problem (script 404) on a Next 13 app (still using `/pages`) with a custom 404 page. disabled & enabled the feature in the vercel UI again and redeployed, still 404ing. It says "Vercel Analytics is set up, but detected a non-production environment." on my local though, so it's at least trying to do something.

**Comment by TedAce** [comment] 2022-10-27 16:05
Same here

**Comment by tobiaslins** [comment] 2022-10-27 18:36
We're actively working on a solution for this issue. We'll keep you posted!

**Comment by sgarcia22** [comment] 2022-10-27 23:15
Same problem, I get a `Uncaught SyntaxError: Unexpected token '<' (at script.js:1:1)` and cannot access any analytics.

I'm using **Vue v2**, and tried injecting it with the `inject()` call in both the app.js `mounted()` callback, and in main.js when creating the Vue app.

Also tried using it in the HTML `<script async src="/va/script.js"></script>`.

In my routes I have this however, not sure if that is causing a problem like the comments above or how I would go about fixing that.
```
  {
    path: "/:catchAll(.*)",
    name: "NotFound",
    redirect: "/",
    meta: {title: "😔 - 404"},
  },
  ```

**Comment by remisture** [comment] 2022-10-28 16:17
> We're actively working on a solution for this issue. We'll keep you posted!

Any updates?

**Comment by aprendendofelipe** [comment] 2022-10-29 16:51
There seems to be an incompatibility with the `i18n` configuration in `next.config.js`.

**Comment by JoshLittlewood** [comment] 2022-10-29 19:34
Removing `i18n` from my next.config.js did resolve the issue for me.

**Comment by paulmwatson** [comment] 2022-11-01 08:40
Happening on our NextJS site hosted on Vercel too. i18n worth more than analytics at the moment so will wait for official fix.

**Comment by tobiaslins** [comment] 2022-11-02 14:15
Hey everyone!
We just rolled out the fix for this issue.
You will have to redeploy your apps to make it work. 

Let us know how it goes 🙌

**Comment by paulmwatson** [comment] 2022-11-02 14:22
Thanks @tobiaslins but I'm getting the same error. Re-enabled the analytics, updated the code, re-deployed, but same  `https://www.somersetstrikers.co.za/va/script.js` 404  error.

**Comment by alex-grover** [comment] 2022-11-02 14:25
I got the analytics to work using the plain HTML approach in my project (didn't even need to install the NPM package). Thank you!

**Comment by joulev** [comment] 2022-11-02 14:25
@tobiaslins Can confirm that it is working now for my app (#5).

**Comment by dglsparsons** [comment] 2022-11-02 14:31
> Thanks @tobiaslins but I'm getting the same error. Re-enabled the analytics, updated the code, re-deployed, but same `https://www.somersetstrikers.co.za/va/script.js` 404 error.

Hi @paulmwatson, it looks like you enabled Analytics after deploying the project. It needs to be enabled before making the deployment. Could you re-deploy again and check? :)

**Comment by frontsideair** [comment] 2022-11-02 14:36
Works for me as well, thanks! As a docs suggestion, I added the inject script to `gatsby-node.js` for Gatsby, as it seemed like the correct place for it.

**Comment by paulmwatson** [comment] 2022-11-02 14:40
Thanks @dglsparsons, just did a re-deploy there (leaving analytics enabled) and same error.

**Comment by dglsparsons** [comment] 2022-11-02 14:51
Okay, it seems like we still have some issues relating to i18n interfering with analytics. We're working on a fix for sites using i18n now. I believe sites without i18n should work fine though.

**Comment by vacodoceo** [comment] 2022-11-02 15:37
@tobiaslins still having the same error with SvelteKit

**Comment by tobiaslins** [comment] 2022-11-02 15:39
@vacodoceo can you please share the last deployment url with us to take a closer look?

**Comment by Robin-w151** [comment] 2022-11-02 16:42
I can confirm that it is now working for my SvelteKit app after I did a redeployment and leaving audiences enabled.

**Comment by dglsparsons** [comment] 2022-11-02 16:58
Hi, further update here: we've shipped a change that should resolve any issues with `i18n` interference. You'll need to redeploy (again) to see the changes, but 🤞 this resolves any remaining issues! Let me know if it doesn't work :)

**Comment by vacodoceo** [comment] 2022-11-02 17:04
@tobiaslins I just checked again and it's working. I enabled audiences, redeployed, and it started working. It's strange because I redeployed a couple of times an hour ago and it didn't work, and I don't think enabling audiences was what fixed it.

Anyway, thanks for the support!

**Comment by tjkohli** [comment] 2022-11-02 17:14
It works with SvelteKit after redeploying! Thank you so much. 🙏🏼

**Comment by paulmwatson** [comment] 2022-11-02 18:40
Excellent, it works now, thanks for the work

**Comment by schnubor** [comment] 2022-11-02 19:48
Works, thanks! :)

**Comment by aprendendofelipe** [comment] 2022-11-02 20:04
Now it's working with **i18n**. Thanks!

**Closed** 2022-11-03 08:41 UTC
Labels: bug

**Comment by FlatMapIO** [comment] 2023-04-21 07:47
More than a year has passed, and this problem still exists

**Comment by Dogtiti** [comment] 2023-04-30 03:38
same issue

**Comment by tobiaslins** [comment] 2023-05-02 06:34
@FlatMapIO @Dogtiti can you please send me a deployment URL so I can take a look for you? Happy to dig deep!

**Comment by Dogtiti** [comment] 2023-05-02 06:47
@tobiaslins https://auto-agentgpt.com/

**Comment by tobiaslins** [comment] 2023-05-02 07:03
@Dogtiti It seems like you've already collected data once with that domain but currently Web Analytics for that project is **disabled**. Head over to the Analytics tab for this project, enable it & redeploy to start collecting data again!

**Comment by Dogtiti** [comment] 2023-05-02 07:05
ok,thanks



---Original---
From: "Tobias ***@***.***&gt;
Date: Tue, May 2, 2023 15:03 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [vercel/analytics] Getting 404 for `script.js` (Issue #1)




 
@Dogtiti It seems like you've already collected data once with that domain but currently Web Analytics for that project is disabled. Head over to the Analytics tab for this project, enable it &amp; redeploy to start collecting data again!

**Comment by reevosolutions** [comment] 2023-06-16 04:52
I think this happens when you integrate the analytics on your project without activating the analytics on Vercel

**Comment by valdemardev01** [comment] 2023-10-26 17:23
Found out that mby if you use addlbock, that will stop the script.js from running.

**Comment by rkreicbergs-sorsera** [comment] 2023-11-15 11:50
We also get 404 errors in Datadog, but not sure it's the same issue.

- We've enabled Analytics for our app and we actually see data in dashboard
- we use the NPM package in our `_app.tsx`:
```
 import { Analytics } from "@vercel/analytics/react"; 
 [....]
<Analytics />
```
- in DataDog we an error about 404 from `https://vitals.vercel-insights.com/v1/view?dsn=vxVf....`
 If I understand corretly, the plugin calls `/_vercel/insights/view` which gets the error and the logs it
 
 - as noted, we do see data in the dashbaord and this issue is intermittent, but seems to happen at least once in 2 days and we've done a bunch of new deployments since enabling it - the problem persists
 - last error today was for sorsera-bzouxhxkx-sorsera.vercel.app

Can any of this be explained by ad blockers? IIUC, that could not explain it - it would simple not call `/_vercel/insights/view` at all and thus we'd not get any errors, no?

**Comment by oucar** [comment] 2024-04-14 16:04
I got the exact same error, in my environment my ad blocker was causing the issue. Disabling it solved the problem.

**Comment by hiroshinishio** [comment] 2024-07-07 12:05
I am encountering this issue in my local not production

```
 GET /_vercel/insights/script.js 404 in 2826ms
```

How can I stop alerting?

**Comment by ValdemarLarsen** [comment] 2024-07-07 12:39
> I am encountering this issue in my local not production
> 
> 
> 
> ```
> 
>  GET /_vercel/insights/script.js 404 in 2826ms
> 
> ```
> 
> 
> 
> How can I stop alerting?

Disable adblock
